image: node:12.16.3

pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "sa-east-1"
                S3_BUCKET: "vuejs-sam-jolteon"
                ACL: "public-read"
                LOCAL_PATH: "dist"
